### ISSUE TITLE
Self host this source on aws lambda

### ISSUE THREAD

**Issue by yunho-medi** [anc95/ChatGPT-CodeReview#131]
Hello! First of all, I really like your project.
 I have a question: I'm currently trying to deploy it on AWS Lambda. Could you please guide me on how to do that?
 Thank you.

**Comment by anc95** [comment]
1. You should prepare the required env variable in the `.env` file
2. `yarn build:lambda` to build the aws lambda function
3. use [serverless]( https://www.serverless.com/framework/docs/getting-started )for deploying. (AWS account is required)

**Comment by yunho-medi** [comment]
thank you :)

one more thing

after deploy how to use it? 

what is format for post request?

**Comment by yunho-medi** [comment]
```
 "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '/var/task/lambda'\nRequire stack:\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '/var/task/lambda'",
        "Require stack:",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1061:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1093:21)",
        "    at async start (file:///var/runtime/index.mjs:1256:23)",
        "    at async file:///var/runtime/index.mjs:1262:1"
    ]
```

after deploy i got above error

what did i miss?

@anc95

**Comment by yunho-medi** [comment]
I found.

in serverless.yml file
change handler path like below
```
    handler: lambda/index.webhooks 
```

**Comment by anc95** [comment]
@yunho-medi You deployed a webhook. Then you should create a github app with the webhook endpoint configured, then install the app to your repo, and event such as a pull request open / sync happened, would invoke the webhook for reviewing
